<script type="text/javascript" src="js/others/jquery.min.js"></script>
<script type="text/javascript" src="js/others/bootstrap.min.js"></script>
<script type="text/javascript" src="js/others/bootbox.min.js"></script>
<script type="text/javascript" src="js/others/jquery.validate.js"></script>
<script type="text/javascript" src="js/others/messages_ptbr.js"></script>
<!-- EJS -->
<script type="text/javascript" src="js/others/ejs-bootmenu.js"></script>
<script type="text/javascript" src="js/others/ejs-boottable.js"></script>
<script type="text/javascript" src="js/others/ejs-bootform.js"></script>
<script type="text/javascript" src="js/others/ejs-bootalert.js"></script>
<script type="text/javascript" src="js/others/ejs-utils.js"></script>
<!-- JS -->
<script type="text/javascript" src="js/emm-nivelacesso.js"></script>
<script type="text/javascript" src="js/emm-login.js"></script>
<script type="text/javascript" src="js/emm-users.js"></script>
<script type="text/javascript" src="js/emm-funcionario.js"></script>
<script type="text/javascript" src="js/scripts.js"></script>
