<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/bootbox.min.js"></script>
<script type="text/javascript" src="js/markdown.js"></script>
<script type="text/javascript" src="js/to-markdown.js"></script>
<script type="text/javascript" src="js/bootstrap-markdown.js"></script>
<script type="text/javascript" src="js/jquery.validate.js"></script>
<script type="text/javascript" src="js/messages_ptbr.js"></script>
<!-- EJS -->
<script type="text/javascript" src="js/bootmenu.js"></script>
<script type="text/javascript" src="js/boottable.js"></script>
<script type="text/javascript" src="js/bootform.js"></script>
<script type="text/javascript" src="js/bootalert.js"></script>
<script type="text/javascript" src="js/ejs-utils.js"></script>
<!-- JS -->
<script type="text/javascript" src="js/emm-nivelacesso.js"></script>
<script type="text/javascript" src="js/emm-status.js"></script>
<script type="text/javascript" src="js/emm-login.js"></script>
<script type="text/javascript" src="js/emm-start.js"></script>
<script type="text/javascript" src="js/emm-users.js"></script>
<script type="text/javascript" src="js/scripts.js"></script>